### ISSUE TITLE
Add the XML Comment Documentation to the Server Project

### ISSUE THREAD

**Issue by efonsecab** [pticostaricags/FairPlaySocial#123]
In the project "FairPlaySocial.Server", enable the Documentation File
<img width="548" alt="image" src="https://user-images.githubusercontent.com/3481899/211437498-541386c8-436f-4a5e-9838-cba09b74477f.png">

Once the documentation is enabled, fix all of the compilation errors by adding the respective XML comments.

**Comment by dsm637** [comment]
Can I take it?

**Comment by efonsecab** [comment]
Hello @dsm637 , yes, you can go ahead and take this task.
Please remember to use the development branch as a base when creating you local branch for this task

**Comment by dsm637** [comment]
Sure. I'm going to go through the Server project and add missing XML comments to classes, methods and parameters. Currently, enabling "Enable API documentation" produces about 100 errors. I presume that Swagger page also should work, correct?

**Comment by efonsecab** [comment]
> Sure. I'm going to go through the Server project and add missing XML comments to classes, methods and parameters. Currently, enabling "Enable API documentation" produces about 100 errors. I presume that Swagger page also should work, correct?

Yes @dsm637 , that's right, the solution purposely handles warnings as errors to create compilation errors for these cases and make it easier to find where the missing comments are.
Indeed, that is for seeing the documentation in the swagger page, you may not be able to load it until you fully configure your Development Environment with the multiple services secrets like Azure Text Analytics, Azure Translator, etc.
We are in the process of making it easier for developers to fully configure their environments, for now, it is enough for the solutions to compile once the comments have been added.

**Comment by dsm637** [comment]
There are bunch of auto-generated controllers (*g.cs). Is there a way to suppress the 1591 warning for them? Or there is a better way? Just couldn't find it.

**Comment by efonsecab** [comment]
Hello @dsm637, I was expecting those not to cause issues.
This is what can be done to avoid the autogenerated code to show errors
In the project "FairPlaySocial.Server.Generators", file "ControllersIncrementalGenerator.cs",
add the supress lines  right before the namespace, and right before the line indicating the file name
<img width="605" alt="image" src="https://user-images.githubusercontent.com/3481899/212475725-fb2699e7-102c-4b76-8828-1bbdbe628fa5.png">

<img width="659" alt="image" src="https://user-images.githubusercontent.com/3481899/212475767-b8ebec06-4199-483b-80cc-8756c7705b52.png">

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member


That will cause the errors disappears for the auto generated code.
After the change, you may need to restart Visual Studio so these errors are not shown anymore

**Comment by efonsecab** [comment]
@all-contributors please add @dsm637 for code
