### ISSUE TITLE
Create a new table named Group

### ISSUE THREAD

**Issue by efonsecab** [pticostaricags/FairPlaySocial#42]
Create a new table named Group, with the following columns
* GroupId
* OwnerApplicationUserId
* Name
* Description
* TopicTag
* IOriginatorInfo interface columns

**Comment by tarunsamanta2k20** [comment]
I would like to contribute to this issue. Please assign it to me.

**Comment by efonsecab** [comment]
> I would like to contribute to this issue. Please assign it to me.

Sure @tarunsamanta2k20 , item is now assigned to you, please let me know if you have any doubts
