### ISSUE TITLE
Apply recommendations from Visual Studio Code Analyzer

### ISSUE THREAD

**Issue by efonsecab** [pticostaricags/FairPlaySocial#51]
**Note: For this task, ignore the MAUI project.**

Apply recommendations from Visual Studio Code Analyzer, make sure to run it multiple times after apply the recommendations, since, initially, not all of them may show up.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/3481899/209668268-1a3cac61-b929-4b7a-90c3-b20c7e95a5f1.png">

<img width="615" alt="image" src="https://user-images.githubusercontent.com/3481899/209668329-0d40c247-d1cd-4393-9e33-e618745e01d0.png">

**Comment by dsm637** [comment]
I could take it.

**Comment by efonsecab** [comment]
> I could take it.

Sure, feel free to take it.

**Comment by dsm637** [comment]
What about those ones:
![image](https://user-images.githubusercontent.com/3065200/212782323-0c74b44f-ab23-4157-a148-58ec14cfb10e.png)
Should we update async calls by passing the cancellationToken, use CancellationToken.None or what?
Here, for instance, we're passing the existing token:
![image](https://user-images.githubusercontent.com/3065200/212782570-1abe30fd-3821-4c2b-9240-fc44213363ce.png)

**Comment by efonsecab** [comment]
> What about those ones: ![image](https://user-images.githubusercontent.com/3065200/212782323-0c74b44f-ab23-4157-a148-58ec14cfb10e.png) Should we update async calls by passing the cancellationToken, use CancellationToken.None or what? Here, for instance, we're passing the existing token: ![image](https://user-images.githubusercontent.com/3065200/212782570-1abe30fd-3821-4c2b-9240-fc44213363ce.png)

Please use the CancellationToken received in the methods signature.

For the Client Services, pass the base.CancellationToken, when available, if the page or component is not inheriting from CustomBaseComponent, just pass CancellatioToken.None instead.

For the Services, pass the cancellationToken received in the controller method calling the service.
