### ISSUE TITLE
Create the GroupModerator table

### ISSUE THREAD

**Issue by efonsecab** [pticostaricags/FairPlaySocial#59]
Create the table "GroupModerator" with the following columns
* GroupModeratorId (BIGINT, NOT NULL, PK_GroupModerator, IDENTITY)
* GroupId (BIGINT,  NOT NULL, Foreign Key to Group)
* ModeratorApplicationUserId (BIGINT, NOT NULL, Foreign Key to ApplicationUser)
* IOriginatorInfo interface columns

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign it to me.
