### ISSUE TITLE
Create the table PostReach

### ISSUE THREAD

**Issue by efonsecab** [pticostaricags/FairPlaySocial#61]
Create the table "PostReach" with the following columns
* PostReachId (BIGINT, NOT NULL, PK_PostReach, IDENTITY)
* ReachedByApplicationUserId (BIG INT, NOT NULL, Foreign Key to ApplicationUser)
* IOriginatorInfo interface columns

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign it to me.
